spring:
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:mysql://moohaehan-db-instance.civaiflao2cd.ap-northeast-2.rds.amazonaws.com:3306/moohaehan
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: moohaehan
    password: moo220327!
  jpa:
    hibernate:
      ddl-auto: validate