server:
  # nginx default port 가 5000
  port: 5000
  max-http-header-size: 400000

spring:
  config:
    use-legacy-processing: true
  profiles:
    include:
      - database
      - oauth2_authorization_server
      - oauth2_client_server
      - seoulapi
      - aws
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

upload_path: ./moohaehan/files

init_data: false

http_https: https://
server_domain: api.moohaehan.com
service_domain: api.moohaehan.com