server:
  port: 8080

spring:
  profiles:
    active: local
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:mariadb://zep-database.crtzkg9a7sbf.ap-northeast-2.rds.amazonaws.com:3306/zep
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password: dla00ckd!!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

init_data: true

http_https: http://
server_domain: localhost:8080
service_domain: localhost:8080
